" basic configuration{
set ts=4
set sts=4
set shiftwidth=4
set nu
set expandtab
set cindent
set autoindent
set encoding=utf-8

syntax enable
syntax on
filetype plugin indent on
filetype on

"set numap ,
let mapleader=","

set showmatch
set hlsearch
set incsearch
"set list
set textwidth=80
set cursorline
set showmode
noremap j gj
noremap k gk
inoremap jj <ESC>

" 分屏窗口移动, Smart way to move between windows
map <C-j> <C-W>j
map <C-k> <C-W>k
map <C-h> <C-W>h
map <C-l> <C-W>l

cmap w!! w !sudo tee >/dev/null %

" Is better way to zoom windows in Vim than ZoomWin?
" Zoom / Restore window.
function! s:ZoomToggle() abort
    if exists('t:zoomed') && t:zoomed
        execute t:zoom_winrestcmd
        let t:zoomed = 0
    else
        let t:zoom_winrestcmd = winrestcmd()
        resize
        vertical resize
        let t:zoomed = 1
    endif
endfunction
command! ZoomToggle call s:ZoomToggle()
nnoremap <silent> <Leader>z :ZoomToggle<CR>
"}

" bundle setting{
    if filereadable(expand("~/.vimrc.bundle"))
        source ~/.vimrc.bundle
    endif
" }


"  UI setting  {
   set background=dark
   if filereadable(expand("~/.vim/bundle/vim-colors-solarized/colors/solarized.vim"))
       let g:solarized_termcolors=256
       let g:solarized_termtrans=1
       let g:solarized_contrast="normal"
       let g:solarized_visibility="normal"
       color solarized
   endif
   if &term == 'xterm' || &term == 'screen' 
       set t_Co=256
   endif

" }

" Identify platform {
    silent function! OSX()
        return has('macunix')
    endfunction
    silent function! LINUX()
        return has('unix') && !has('macunix') && !has('win32unix')
    endfunction
    silent function! WINDOWS()
        return  (has('win32') || has('win64'))
    endfunction

" }

" keys-binding {
"nmap <c-F5> :!g++ % -o out -std=c++11 && ./out<CR>
nmap <C-F5> :call CompileFile()<CR>
nmap <Leader>xx :call CompileFile()<CR>

func! CompileFile()
    if &filetype == 'cpp'
        exec "!g++ % -o out -std=c++11 && ./out && rm ./out"
    elseif &filetype =='c'
        exec "!gcc % -o out && ./out && rm ./out"
    elseif &filetype == 'python'
        exec "!python %"
    elseif &filetype == "sh"
        exec "!bash %"
    endif
endfunc

nmap <C-F10> :call UpdateCtags()<CR><CR>
nmap <silent> <F10> :call GenerateCtags()<CR><CR>

function! GenerateCtags()
    !ctags -R --file-scope=yes --langmap=c:+.h --languages=c,c++ --links=yes --c-kinds=+p --c++-kinds=+p --fields=+iaS --extra=+q
endfunction

function! UpdateCtags()
    let curdir=getcwd()
    while !filereadable("./tags")
        cd ..
        if getcwd() == "/"
            break
        endif
    endwhile
    if filewritable("./tags")
        !ctags -R --file-scope=yes --langmap=c:+.h --languages=c,c++ --links=yes --c-kinds=+p --c++-kinds=+p --fields=+iaS --extra=+q
        TlistUpdate
    endif
    execute ":cd " . curdir
endfunction

" }

" self-specific {
function! PrintList(...)
    for line in a:000
        execute "normal! o"
        execute "normal! 0d$i".line
    endfor
endfunction

" }

" local setting {
    if filereadable(expand("~/.vimrc.local"))
        source ~/.vimrc.local
    endif
" }
